"""Per-section documentation generation.

This module orchestrates the creation of all documentation markdown files.  It
produces two kinds of content:

1.  **LLM-authored sections** — one API call per section (Getting Started,
    Guides, Framework Integrations, Advanced Usage, Troubleshooting).  Each
    call is fed a compact IR slice + curated context (README, changelog,
    examples).  The LLM is instructed to never invent APIs.

2.  **Deterministic API Reference** — rendered directly from the IR using
    templates.  This is guaranteed accurate because it is derived
    mechanically from the AST, not generated by a model.

The home page (``index.md``) is also rendered deterministically from the IR
and README head.
"""
from __future__ import annotations

from dataclasses import asdict
from typing import Callable

from .analyzer import ClassIR, FunctionIR, ModuleIR, PackageIR, ParamIR


# ---------------------------------------------------------------------------
# LLM-authored sections
# ---------------------------------------------------------------------------
# Each tuple is (section_key, section_title, extra_instructions).
# The key is used as the output filename (e.g. ``getting_started.md``).
# The title is the H1 added by ``_ensure_h1``.
# The extra instructions are appended to the system prompt for that section.

LLM_SECTIONS: list[tuple[str, str, str]] = [
    ("getting_started", "Getting Started",
     "Cover installation, authentication (API keys / env vars if referenced in "
     "README), and a minimal 'hello world' example using the primary client."),
    ("guides", "Guides",
     "Task-oriented how-to guides for the most common workflows. One H2 per "
     "guide. Prefer end-to-end runnable snippets."),
    ("framework_integrations", "Framework Integrations",
     "How to use this SDK with popular frameworks (Flask, FastAPI, Django, "
     "async loops, background workers) *only if applicable*. If not, produce "
     "a short 'Framework-agnostic' note instead of inventing integrations."),
    ("advanced_usage", "Advanced Usage",
     "Advanced patterns: retries, pagination, streaming, custom transports, "
     "concurrency, extending base classes. Only include what the IR supports."),
    ("troubleshooting", "Troubleshooting",
     "Common errors and how to diagnose them. Use the IR's exception classes "
     "(if any) and the README/changelog for known issues."),
]


# ---------------------------------------------------------------------------
# IR slicing
# ---------------------------------------------------------------------------
# The full IR can be large.  We compact it per-section so the prompt stays
# within budget.  All sections get the same lean view; the LLM is told which
# aspects to emphasise via the ``extra`` instructions.

def _ir_slice_for_section(section_key: str, pkg: PackageIR) -> dict:
    """Build a compact IR dict suitable for sending to the LLM.

    The slice includes:
        - package name
        - per-module: path, dotted module name, docstring head, classes
          (name, bases, docstring head, public methods), public functions,
          ``__all__`` exports
        - a list of "primary clients" (classes ending in Client/API/SDK)

    Everything is truncated to keep the payload small.
    """
    modules = []
    for m in pkg.modules:
        modules.append({
            "path": m.path,
            "module": m.module,
            "docstring": (m.docstring or "")[:600],
            "classes": [
                {
                    "name": c.name,
                    "qualname": c.qualname,
                    "bases": c.bases,
                    "docstring": (c.docstring or "")[:600],
                    "methods": [_fn_summary(fn) for fn in c.methods if not fn.is_private][:30],
                }
                for c in m.classes
            ],
            "functions": [_fn_summary(fn) for fn in m.functions if not fn.is_private][:20],
            "all_exports": m.all_exports,
        })
    return {"package": pkg.name, "modules": modules,
            "primary_clients": _primary_clients(pkg)}


def _fn_summary(fn: FunctionIR) -> dict:
    """Compact summary of a function/method for the IR slice."""
    return {
        "name": fn.name,
        "qualname": fn.qualname,
        "async": fn.is_async,
        "signature": _signature(fn),
        "returns": fn.returns,
        "docstring": (fn.docstring or "")[:400],
    }


def _signature(fn: FunctionIR) -> str:
    """Reconstruct a human-readable function signature string."""
    parts = []
    for p in fn.params:
        s = p.name
        if p.kind == "vararg":
            s = f"*{p.name}"
        elif p.kind == "kwarg":
            s = f"**{p.name}"
        if p.annotation:
            s += f": {p.annotation}"
        if p.default is not None:
            s += f" = {p.default}"
        parts.append(s)
    sig = f"{'async ' if fn.is_async else ''}{fn.name}({', '.join(parts)})"
    if fn.returns:
        sig += f" -> {fn.returns}"
    return sig


def _primary_clients(pkg: PackageIR) -> list[str]:
    """Find classes whose names end in Client/API/SDK — the likely entry points."""
    hits = []
    for m in pkg.modules:
        for c in m.classes:
            if c.name.endswith(("Client", "API", "SDK")):
                hits.append(c.qualname)
    return hits[:10]


# ---------------------------------------------------------------------------
# Deterministic API Reference rendering
# ---------------------------------------------------------------------------
# These functions produce markdown directly from the IR — no LLM involved.
# This guarantees the API reference is accurate and complete.

def render_api_reference(pkg: PackageIR) -> dict[str, str]:
    """One markdown file per module. Returns ``{ relative_docs_path: markdown }``.

    Filenames are placed under ``api/`` inside the docs tree.
    """
    files: dict[str, str] = {}
    for m in pkg.modules:
        if not (m.classes or [f for f in m.functions if not f.is_private]):
            continue
        files[f"api/{m.module.replace('.', '/')}.md"] = _render_module_md(m)
    files["api/index.md"] = _render_api_index(pkg)
    return files


def _render_api_index(pkg: PackageIR) -> str:
    """Render the API reference index page."""
    lines = ["# API Reference", "",
             f"Auto-generated reference for **{pkg.name}**.", ""]
    for m in pkg.modules:
        if not (m.classes or [f for f in m.functions if not f.is_private]):
            continue
        lines.append(f"- [`{m.module}`]({m.module.replace('.', '/')}.md)")
    return "\n".join(lines) + "\n"


def _render_module_md(m: ModuleIR) -> str:
    """Render a single module's API reference page."""
    out: list[str] = [f"# `{m.module}`", ""]
    if m.docstring:
        out.append(m.docstring.strip())
        out.append("")
    if m.all_exports:
        out.append("**Exports:** " + ", ".join(f"`{n}`" for n in m.all_exports))
        out.append("")

    if m.classes:
        out.append("## Classes")
        out.append("")
        for c in m.classes:
            out.append(_render_class_md(c))
            out.append("")

    pub_fns = [f for f in m.functions if not f.is_private]
    if pub_fns:
        out.append("## Functions")
        out.append("")
        for fn in pub_fns:
            out.append(_render_fn_md(fn, heading_level=3))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def _render_class_md(c: ClassIR) -> str:
    """Render a single class's API reference section."""
    lines = [f"### `class {c.name}`"]
    if c.bases:
        clean = [b for b in c.bases if b]
        if clean:
            lines.append("")
            lines.append(f"*Bases:* {', '.join(f'`{b}`' for b in clean)}")
    lines.append("")
    if c.docstring:
        lines.append(c.docstring.strip())
        lines.append("")
    public_methods = [m for m in c.methods if not m.is_private]
    if public_methods:
        lines.append("#### Methods")
        lines.append("")
        for fn in public_methods:
            lines.append(_render_fn_md(fn, heading_level=5))
            lines.append("")
    return "\n".join(lines).rstrip()


def _render_fn_md(fn: FunctionIR, heading_level: int = 3) -> str:
    """Render a single function/method's API reference entry."""
    hashes = "#" * heading_level
    tags = []
    if fn.is_async:
        tags.append("async")
    if fn.is_classmethod:
        tags.append("classmethod")
    if fn.is_staticmethod:
        tags.append("staticmethod")
    tag_str = f" _{' '.join(tags)}_" if tags else ""
    parts = [f"{hashes} `{fn.name}(...)`{tag_str}", "",
             "```python", _signature(fn), "```", ""]
    if fn.docstring:
        parts.append(fn.docstring.strip())
        parts.append("")
    # Parameter table
    if fn.params:
        parts.append("| Parameter | Type | Default |")
        parts.append("|-----------|------|---------|")
        for p in fn.params:
            if p.name == "self":
                continue
            parts.append(
                f"| `{_param_disp(p)}` | "
                f"{('`' + p.annotation + '`') if p.annotation else '—'} | "
                f"{('`' + p.default + '`') if p.default is not None else '—'} |"
            )
        parts.append("")
    if fn.returns:
        parts.append(f"**Returns:** `{fn.returns}`")
    return "\n".join(parts).rstrip()


def _param_disp(p: ParamIR) -> str:
    """Format a parameter name for display (handles *args / **kwargs)."""
    if p.kind == "vararg":
        return f"*{p.name}"
    if p.kind == "kwarg":
        return f"**{p.name}"
    return p.name


# ---------------------------------------------------------------------------
# Full generation orchestration
# ---------------------------------------------------------------------------

def generate_docs(pkg: PackageIR, context: dict,
                  llm_writer: Callable[[str, dict, dict, str], str] | None = None,
                  progress: Callable[[str], None] | None = None) -> dict[str, str]:
    """Return ``{ docs_relative_path: markdown }`` covering all sections.

    Parameters
    ----------
    pkg
        The package IR from ``analyzer.analyze()``.
    context
        Curated context (README, changelog, examples) from
        ``analyzer.gather_context()``.
    llm_writer
        Optional override for the LLM callable (useful for testing).  Defaults
        to ``llm.write_section``.
    progress
        Optional callback for progress logging (called with a status string).
    """
    from . import llm as _llm
    writer = llm_writer or _llm.write_section

    files: dict[str, str] = {}

    # --- Home page (deterministic) -----------------------------------------
    files["index.md"] = _render_home(pkg, context)

    # --- LLM-authored sections ---------------------------------------------
    ir_slice = _ir_slice_for_section("all", pkg)
    for key, title, extra in LLM_SECTIONS:
        if progress:
            progress(f"generating section: {title}")
        try:
            md = writer(title, ir_slice, context, extra)
        except Exception as e:  # noqa: BLE001
            # If the LLM fails for this section, emit a warning placeholder
            # so the rest of the docs still build.
            md = (f"# {title}\n\n"
                  f"!!! warning\n    This section could not be generated: {e}\n")
        files[f"{key}.md"] = _ensure_h1(md, title)

    # --- Deterministic API reference ---------------------------------------
    if progress:
        progress("rendering API reference from IR")
    files.update(render_api_reference(pkg))
    return files


def _ensure_h1(md: str, title: str) -> str:
    """Ensure the markdown starts with an H1 heading (if not already present)."""
    stripped = md.lstrip()
    if stripped.startswith("# "):
        return md
    return f"# {title}\n\n{md}"


def _render_home(pkg: PackageIR, context: dict) -> str:
    """Render the home page from the README head + a navigation hint."""
    readme = (context or {}).get("readme") or ""
    intro = ""
    if readme:
        # Take up to the first horizontal rule or first ~1200 chars.
        head = readme.split("\n## ", 1)[0]
        intro = head.strip()[:1500]
    parts = [f"# {pkg.name}", ""]
    if intro:
        parts.append(intro)
        parts.append("")
    parts.append("Use the navigation to explore the documentation.")
    return "\n".join(parts) + "\n"